name: Node.js CI

on:
  push:
    branches:
      - testing

env:
  PORT: ${{ secrets.PORT }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build --if-present
      - name: Start PM2 process manager
        run: sudo pm2 restart "backend" && sudo pm2 save
      - name: Show PM2 Process
        run: sudo pm2 list

  # Note: This assumes that the user running the workflow has permission to run `pm2 restart`
